name: Deploy to Digital Ocean
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
          config: |
            Host *
              StrictHostKeyChecking no
          name: id_rsa
          
      - name: Set SSH key permissions
        run: chmod 600 ~/.ssh/id_rsa
      
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
      
      - name: Deploy with rsync
        run: |
          rsync -avz --delete ./ ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }}:/var/www/html/
          ssh ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} '
            cd /var/www/html && 
            sudo chown -R www-data:www-data . &&
            sudo chmod -R 755 . &&
            sudo systemctl restart apache2
          ' 